services:
  toniedownloader:
    image: toniedownloader
    user: 1000:1000
    container_name: toniedownloader
    restart: 'unless-stopped'
    env_file:
      - .env
    ports:
      - 40012:4000

  toniedownloader-chrigi:
    image: toniedownloader
    user: 1000:1000
    container_name: toniedownloader-chrigi
    restart: 'unless-stopped'
    env_file:
      - .env.chrigi
    ports:
      - 40013:4000
