services:
  tonie:
    image: tonie
    user: 1000:1000
    container_name: tonie
    restart: 'unless-stopped'
    env_file:
      - .env
    environment:
      - PHX_HOST=localhost
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    ports:
      - 4000:4000
